import Head from "next/head";
import LoginForm from "../components/forms/loginForm";
import Button from "../components/button";
import { gql } from "@apollo/client";
import { useRouter } from "next/router";
import Image from "next/image";
import PiggyBank from "../public/assets/Savings-bro.svg";

const GET_USERS = gql`
  query get_all_users {
    users {
      id
      fullName
      website
      emailAddress
      password
    }
  }
`;

export default function Home() {
  const router = useRouter();

  return (
    <div className="p-3 container flex justify-center items-center h-screen">
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <div className="bg-white md:p-10 text-xl md:flex ">
          <div className="md:w-1/2 md:p-10">
            <h1 className="text-4xl text-bold">Expense Tracker</h1>
            <br />
            <p className="hidden md:block">
              Track your expenses using this Full-Stack application build using
              NextJS, Tailwind CSS, GraphQL, ApolloJS, PrismaJS, and PostgreSQL.{" "}
            </p>
            <br />{" "}
            <div className="flex justify-center items-center">
              <Image
                src={PiggyBank}
                alt="Keep track of your expenses"
                width={150}
                height={150}
                className="mx-auto block"
              />
            </div>
          </div>
          <div className="md:w-1/2 md:p-10 ">
            <LoginForm />
            <p className="text-center text-[grey] p-2">Or</p>
            <Button to="signup">Sign Up</Button>
          </div>
        </div>
      </main>
    </div>
  );
}
