import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LoginForm from "../components/forms/loginForm";
import Button from "../components/button";
import { useQuery, gql } from "@apollo/client";

const GET_USERS = gql`
  query get_all_users {
    users {
      id
      fullName
      website
      emailAddress
      password
    }
  }
`;

export default function Home() {
  return (
    <div className="p-3 container flex justify-center items-center h-screen">
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <div className="bg-white md:p-10 text-xl md:flex ">
          <div className="md:w-1/2 md:p-10">
            <h2 className="text-lg">Expense Tracker</h2> <br />
            <p>
              Track your expenses using this Full-Stack application build using
              NextJS, Tailwind CSS, GraphQL, ApolloJS, PrismaJS, and PostgreSQL.{" "}
              <br /> <br />
              Sign up or login to track your expenses!
            </p>
          </div>
          {/* {console.log(data)} */}
          <div className="md:w-1/2 md:p-10 ">
            <LoginForm />
            <p className="text-center text-[grey] p-2">Or</p>
            <Button>Sign Up</Button>
          </div>
        </div>
      </main>

      {/* <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}

// className={styles.container}
// className={styles.main}
//className={styles.logo}
//className={styles.footer}
//<div className="p-3 container flex justify-center items-center h-screen">
