import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LoginForm from "../components/forms/loginForm";
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  useQuery,
  gql,
  useReactiveVar,
} from "@apollo/client";

// const client = new ApolloClient({
//   uri: "http://localhost:4000/graphql",
//   cache: new InMemoryCache(),
// });

// client
//   .query({
//     query: gql`
//       query getAllUsers {
//         getAllUsers {
//           id
//           fullName
//           website
//           emailAddress
//         }
//       }
//     `,
//   })
//   .then((result) => console.log(result));

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="container flex bg-white p-10">
          <div className="w-1/2">
            <h2 className="text-lg">Expense Tracker</h2> <br />
            <p>
              Track your expenses using this Full-Stack application build using
              NextJS, Tailwind CSS, GraphQL, ApolloJS, PrismaJS, and PostgreSQL.{" "}
              <br /> <br />
              Sign up or login to track your expenses!
            </p>
          </div>

          <div className="w-1/2">
            <LoginForm />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
